apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: meshr
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tflynn3/meshr.git
  ref:
    branch: main
  secretRef:
    name: meshr-git-auth
