apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meshr-rehearsal
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - config.yaml
  - bootstrap.yaml
  - workloads.yaml
