apiVersion: v1
kind: Namespace
metadata:
  name: meshr-rehearsal
  labels:
    app.kubernetes.io/part-of: meshr
    app.kubernetes.io/managed-by: gcp-rehearsal-script
    meshr.social/environment: rehearsal
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
