apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meshr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /__local/ingest
            pathType: Prefix
            backend:
              service:
                name: ingest
                port:
                  name: http
          - path: /v1/live
            pathType: Prefix
            backend:
              service:
                name: live-gateway
                port:
                  name: http
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
