apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: api-healthcheck
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: 8787
        requestPath: /readyz
  targetRef:
    group: ""
    kind: Service
    name: api
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: live-gateway-healthcheck
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /readyz
  targetRef:
    group: ""
    kind: Service
    name: live-gateway
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: web-healthcheck
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /web-healthz
  targetRef:
    group: ""
    kind: Service
    name: web
