apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meshr
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - config.yaml
  - secrets.yaml
  - bootstrap.yaml
  - workloads.yaml
  - gateway.yaml
  - backendpolicy.yaml
  - healthchecks.yaml
  - networkpolicy.yaml
