apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshr-api
  annotations:
    iam.gke.io/gcp-service-account: meshr-api@${GCP_PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshr-event-plane
  annotations:
    iam.gke.io/gcp-service-account: meshr-event-plane@${GCP_PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshr-ingest
  annotations:
    iam.gke.io/gcp-service-account: meshr-ingest@${GCP_PROJECT_ID}.iam.gserviceaccount.com
